<?php

declare(strict_types=1);

namespace AbnServiceSDK;

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'ABRSearchByABN' => '\\AbnServiceSDK\\StructType\\ABRSearchByABN',
            'ABRSearchByABNResponse' => '\\AbnServiceSDK\\StructType\\ABRSearchByABNResponse',
            'Payload' => '\\AbnServiceSDK\\StructType\\Payload',
            'ExternalRequest' => '\\AbnServiceSDK\\StructType\\ExternalRequest',
            'ExternalRequestNameSearch' => '\\AbnServiceSDK\\StructType\\ExternalRequestNameSearch',
            'ExternalRequestFilters' => '\\AbnServiceSDK\\StructType\\ExternalRequestFilters',
            'ExternalRequestFilterNameType' => '\\AbnServiceSDK\\StructType\\ExternalRequestFilterNameType',
            'ExternalRequestFilterStateCode' => '\\AbnServiceSDK\\StructType\\ExternalRequestFilterStateCode',
            'ExternalRequestNameSearchAdvanced' => '\\AbnServiceSDK\\StructType\\ExternalRequestNameSearchAdvanced',
            'ExternalRequestNameSearchAdvanced2006' => '\\AbnServiceSDK\\StructType\\ExternalRequestNameSearchAdvanced2006',
            'ExternalRequestNameSearchAdvanced2012' => '\\AbnServiceSDK\\StructType\\ExternalRequestNameSearchAdvanced2012',
            'ExternalRequestFilters2012' => '\\AbnServiceSDK\\StructType\\ExternalRequestFilters2012',
            'ExternalRequestFilterNameType2012' => '\\AbnServiceSDK\\StructType\\ExternalRequestFilterNameType2012',
            'ExternalRequestFilters2017' => '\\AbnServiceSDK\\StructType\\ExternalRequestFilters2017',
            'ExternalRequestNameSearchAdvanced2017' => '\\AbnServiceSDK\\StructType\\ExternalRequestNameSearchAdvanced2017',
            'ExternalRequestNameSearchAdvanced2023' => '\\AbnServiceSDK\\StructType\\ExternalRequestNameSearchAdvanced2023',
            'ExternalRequestFilters2023' => '\\AbnServiceSDK\\StructType\\ExternalRequestFilters2023',
            'ExternalRequestFilterNameType2023' => '\\AbnServiceSDK\\StructType\\ExternalRequestFilterNameType2023',
            'ExternalRequestABNFilter' => '\\AbnServiceSDK\\StructType\\ExternalRequestABNFilter',
            'ExternalRequestABNCharityFilter' => '\\AbnServiceSDK\\StructType\\ExternalRequestABNCharityFilter',
            'ExternalRequestABNUpdateEventFilter' => '\\AbnServiceSDK\\StructType\\ExternalRequestABNUpdateEventFilter',
            'ExternalRequestABNStatusFilter' => '\\AbnServiceSDK\\StructType\\ExternalRequestABNStatusFilter',
            'ExternalRequestABNEventFilter' => '\\AbnServiceSDK\\StructType\\ExternalRequestABNEventFilter',
            'ExternalRequestIdentifierSearch' => '\\AbnServiceSDK\\StructType\\ExternalRequestIdentifierSearch',
            'Response' => '\\AbnServiceSDK\\StructType\\Response',
            'ResponseBusinessEntity' => '\\AbnServiceSDK\\StructType\\ResponseBusinessEntity',
            'ResponseBody' => '\\AbnServiceSDK\\StructType\\ResponseBody',
            'ResponseSearchResultsList' => '\\AbnServiceSDK\\StructType\\ResponseSearchResultsList',
            'SearchResultsRecord' => '\\AbnServiceSDK\\StructType\\SearchResultsRecord',
            'IdentifierSummary' => '\\AbnServiceSDK\\StructType\\IdentifierSummary',
            'IndividualSimpleName' => '\\AbnServiceSDK\\StructType\\IndividualSimpleName',
            'Individual' => '\\AbnServiceSDK\\StructType\\Individual',
            'IndividualName' => '\\AbnServiceSDK\\StructType\\IndividualName',
            'OrganisationSimpleName' => '\\AbnServiceSDK\\StructType\\OrganisationSimpleName',
            'Organisation' => '\\AbnServiceSDK\\StructType\\Organisation',
            'OrganisationName' => '\\AbnServiceSDK\\StructType\\OrganisationName',
            'AddressSimple' => '\\AbnServiceSDK\\StructType\\AddressSimple',
            'Address' => '\\AbnServiceSDK\\StructType\\Address',
            'AddressFull' => '\\AbnServiceSDK\\StructType\\AddressFull',
            'AddressDetails' => '\\AbnServiceSDK\\StructType\\AddressDetails',
            'ResponseABNList' => '\\AbnServiceSDK\\StructType\\ResponseABNList',
            'ResponseException' => '\\AbnServiceSDK\\StructType\\ResponseException',
            'ResponseBusinessEntity201408' => '\\AbnServiceSDK\\StructType\\ResponseBusinessEntity201408',
            'Identifier' => '\\AbnServiceSDK\\StructType\\Identifier',
            'EntityStatus' => '\\AbnServiceSDK\\StructType\\EntityStatus',
            'EntityType' => '\\AbnServiceSDK\\StructType\\EntityType',
            'GoodsAndServicesTax' => '\\AbnServiceSDK\\StructType\\GoodsAndServicesTax',
            'DgrEndorsementAndItemNumber' => '\\AbnServiceSDK\\StructType\\DgrEndorsementAndItemNumber',
            'DGREndorsement' => '\\AbnServiceSDK\\StructType\\DGREndorsement',
            'DgrFundAndItemNumber' => '\\AbnServiceSDK\\StructType\\DgrFundAndItemNumber',
            'DgrFund' => '\\AbnServiceSDK\\StructType\\DgrFund',
            'CharityType' => '\\AbnServiceSDK\\StructType\\CharityType',
            'CharityConcession' => '\\AbnServiceSDK\\StructType\\CharityConcession',
            'CharitableFund' => '\\AbnServiceSDK\\StructType\\CharitableFund',
            'SuperannuationStatus' => '\\AbnServiceSDK\\StructType\\SuperannuationStatus',
            'Registration' => '\\AbnServiceSDK\\StructType\\Registration',
            'ResponseBusinessEntity202001' => '\\AbnServiceSDK\\StructType\\ResponseBusinessEntity202001',
            'AwefEntity' => '\\AbnServiceSDK\\StructType\\AwefEntity',
            'ResponseBusinessEntity200506' => '\\AbnServiceSDK\\StructType\\ResponseBusinessEntity200506',
            'ResponseBusinessEntity200709' => '\\AbnServiceSDK\\StructType\\ResponseBusinessEntity200709',
            'ResponseBusinessEntity201205' => '\\AbnServiceSDK\\StructType\\ResponseBusinessEntity201205',
            'SearchByABNv200506' => '\\AbnServiceSDK\\StructType\\SearchByABNv200506',
            'SearchByABNv200506Response' => '\\AbnServiceSDK\\StructType\\SearchByABNv200506Response',
            'SearchByABNv200709' => '\\AbnServiceSDK\\StructType\\SearchByABNv200709',
            'SearchByABNv200709Response' => '\\AbnServiceSDK\\StructType\\SearchByABNv200709Response',
            'SearchByABNv201205' => '\\AbnServiceSDK\\StructType\\SearchByABNv201205',
            'SearchByABNv201205Response' => '\\AbnServiceSDK\\StructType\\SearchByABNv201205Response',
            'SearchByABNv201408' => '\\AbnServiceSDK\\StructType\\SearchByABNv201408',
            'SearchByABNv201408Response' => '\\AbnServiceSDK\\StructType\\SearchByABNv201408Response',
            'SearchByABNv202001' => '\\AbnServiceSDK\\StructType\\SearchByABNv202001',
            'SearchByABNv202001Response' => '\\AbnServiceSDK\\StructType\\SearchByABNv202001Response',
            'ABRSearchByASIC' => '\\AbnServiceSDK\\StructType\\ABRSearchByASIC',
            'ABRSearchByASICResponse' => '\\AbnServiceSDK\\StructType\\ABRSearchByASICResponse',
            'SearchByASICv200506' => '\\AbnServiceSDK\\StructType\\SearchByASICv200506',
            'SearchByASICv200506Response' => '\\AbnServiceSDK\\StructType\\SearchByASICv200506Response',
            'SearchByASICv201205' => '\\AbnServiceSDK\\StructType\\SearchByASICv201205',
            'SearchByASICv201205Response' => '\\AbnServiceSDK\\StructType\\SearchByASICv201205Response',
            'SearchByASICv201408' => '\\AbnServiceSDK\\StructType\\SearchByASICv201408',
            'SearchByASICv201408Response' => '\\AbnServiceSDK\\StructType\\SearchByASICv201408Response',
            'ABRSearchByName' => '\\AbnServiceSDK\\StructType\\ABRSearchByName',
            'ABRSearchByNameResponse' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameResponse',
            'ABRSearchByNameAdvanced' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced',
            'ABRSearchByNameAdvancedResponse' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedResponse',
            'ABRSearchByNameAdvanced2006' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced2006',
            'ABRSearchByNameAdvanced2006Response' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced2006Response',
            'ABRSearchByNameAdvanced2012' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced2012',
            'ABRSearchByNameAdvanced2012Response' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced2012Response',
            'ABRSearchByNameAdvanced2017' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced2017',
            'ABRSearchByNameAdvanced2017Response' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced2017Response',
            'ABRSearchByNameAdvanced2023' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced2023',
            'ABRSearchByNameAdvanced2023Response' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvanced2023Response',
            'ABRSearchByNameSimpleProtocol' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameSimpleProtocol',
            'ABRSearchByNameSimpleProtocolResponse' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameSimpleProtocolResponse',
            'ABRSearchByNameAdvancedSimpleProtocol' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol',
            'ABRSearchByNameAdvancedSimpleProtocolResponse' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocolResponse',
            'ABRSearchByNameAdvancedSimpleProtocol2006' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol2006',
            'ABRSearchByNameAdvancedSimpleProtocol2006Response' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol2006Response',
            'ABRSearchByNameAdvancedSimpleProtocol2012' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol2012',
            'ABRSearchByNameAdvancedSimpleProtocol2012Response' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol2012Response',
            'ABRSearchByNameAdvancedSimpleProtocol2017' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol2017',
            'ABRSearchByNameAdvancedSimpleProtocol2017Response' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol2017Response',
            'ABRSearchByNameAdvancedSimpleProtocol2023' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol2023',
            'ABRSearchByNameAdvancedSimpleProtocol2023Response' => '\\AbnServiceSDK\\StructType\\ABRSearchByNameAdvancedSimpleProtocol2023Response',
            'SearchByPostcode' => '\\AbnServiceSDK\\StructType\\SearchByPostcode',
            'SearchByPostcodeResponse' => '\\AbnServiceSDK\\StructType\\SearchByPostcodeResponse',
            'SearchByABNStatus' => '\\AbnServiceSDK\\StructType\\SearchByABNStatus',
            'SearchByABNStatusResponse' => '\\AbnServiceSDK\\StructType\\SearchByABNStatusResponse',
            'SearchByRegistrationEvent' => '\\AbnServiceSDK\\StructType\\SearchByRegistrationEvent',
            'SearchByRegistrationEventResponse' => '\\AbnServiceSDK\\StructType\\SearchByRegistrationEventResponse',
            'SearchByUpdateEvent' => '\\AbnServiceSDK\\StructType\\SearchByUpdateEvent',
            'SearchByUpdateEventResponse' => '\\AbnServiceSDK\\StructType\\SearchByUpdateEventResponse',
            'SearchByCharity' => '\\AbnServiceSDK\\StructType\\SearchByCharity',
            'SearchByCharityResponse' => '\\AbnServiceSDK\\StructType\\SearchByCharityResponse',
            'ActivityReport' => '\\AbnServiceSDK\\StructType\\ActivityReport',
            'ActivityResponse' => '\\AbnServiceSDK\\StructType\\ActivityResponse',
            'ActivityRequest' => '\\AbnServiceSDK\\StructType\\ActivityRequest',
            'ArrayOfActivity' => '\\AbnServiceSDK\\ArrayType\\ArrayOfActivity',
            'Activity' => '\\AbnServiceSDK\\StructType\\Activity',
            'ActivityReportResponse' => '\\AbnServiceSDK\\StructType\\ActivityReportResponse',
        ];
    }
}
